server:
  port: 9001
  tomcat:
    max-threads: 400 # 默认200
    accept-count: 500 # 默认值 100

spring:
  application:
    name: order-handle-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:9950 #dashboard端口
        port: 8719  #默认8719端口，加入被占用+1递增寻找可用端口
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckillproject?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: {就不告诉你}
  redis:
    port: 6379
    host: 39.102.87.156
    password: {就不告诉你}

rocketmq:
  name-server: 39.102.87.156:9876
  producer:
    group: seckillOrderGroup
    send-message-timeout: 5000

mybatis:
  type-aliases-package: com.sauvignon.seckill.pojo.entities
  mapper-locations: classpath:mybatis/mappers/*.xml

#激活OpenFeign对Sentinel的支持
feign:
  sentinel:
    enabled: true
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 4000

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: SEATA_GROUP    #seata事务分组名称
  enable-auto-data-source-proxy: true    #开启数据库代理
  service:
    vgroupMapping:
      SEATA_GROUP: default
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: "SEATA_GROUP"
      namespace: ""
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      cluster: default
      namespace: ""
      username: nacos
      password: nacos

logging:
  level:
    io:
      seata: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

#自定义属性
order-handle:
  service:
    storageService: "commodity-storage-service"
  mq:
    consumerGroup:
      orderConsumer: "seckillOrderHandlerGroup"
      overtimeConsumer: "seckillOrderOvertimeGroup"
    topic: "seckill_order_host_topic"
    tag:
      consumeTag: "consumeTag"
      overTimeTag: "overTimeTag"
