server:
  port: 9001
  tomcat:
    max-threads: 400 # 默认200
    accept-count: 500 # 默认值 100

spring:
  application:
    name: order-handle-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:9950 #dashboard端口
        port: 8719  #默认8719端口，加入被占用+1递增寻找可用端口
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckillproject?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: {}
    druid:
      min-idle: 20
      max-active: 50
      max-wait: 5000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      filters: stat,wall,log4j
      #最大PSCache连接
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 配置StatFilter
      web-stat-filter:
        #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #配置StatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        #允许那些ip
        allow: 127.0.0.1
        login-username: druid
        login-password: druid
        #禁止那些ip
        #        deny: 192.168.1.102
        #是否可以重置
        reset-enable: true
        #启用
        enabled: true
  redis:
    port: 6379
    host: 39.102.87.156
    password: {}
    timeout: 2000
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 12

redisson:
  address: "redis://39.102.87.156:6379"
  password: "{}"

rocketmq:
  name-server: 39.102.87.156:9876
  producer:
    group: seckillOrderGroup
    send-message-timeout: 5000

mybatis:
  type-aliases-package: com.sauvignon.seckill.pojo.entities
  mapper-locations: classpath:mybatis/mappers/*.xml

#激活OpenFeign对Sentinel的支持
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC
  httpclient:
    enabled: true # FeignRibbonClientAutoConfiguration 和 HttpClientFeignLoadBalancedConfiguration
    maxConnections: 200 # 最大连接数，默认值200
    maxConnectionsPerRoute: 50 # 每个host最大使用连接数，默认值50
    connectionTimeout: 2000 # 连接超时时间，默认值2000
    connectionTimerRepeat: 3000 #默认值3000

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: SEATA_GROUP    #seata事务分组名称
  enable-auto-data-source-proxy: true    #开启数据库代理
  service:
    vgroupMapping:
      SEATA_GROUP: default
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: "SEATA_GROUP"
      namespace: ""
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      cluster: default
      namespace: ""
      username: nacos
      password: nacos

logging:
  level:
    io:
      seata: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

#自定义属性
order-handle:
  service:
    storageService: "commodity-storage-service"
  mq:
    consumerGroup:
      orderConsumer: "seckillOrderHandlerGroup"
      overtimeConsumer: "seckillOrderOvertimeGroup"
    topic: "seckill_order_host_topic"
    tag:
      consumeTag: "consumeTag"
      overTimeTag: "overTimeTag"
