server:
  port: 9002
  tomcat:
    max-threads: 400 # 默认200
    accept-count: 500 # 默认值 100

spring:
  application:
    name: commodity-storage-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:9950 #dashboard端口
        port: 8719  #默认8719端口，加入被占用+1递增寻找可用端口
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckillproject?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: Zx7895204163+
    druid:
      min-idle: 20
      max-active: 50
      max-wait: 5000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      filters: stat,wall,log4j
      #最大PSCache连接
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 配置StatFilter
      web-stat-filter:
        #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #配置StatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        #允许那些ip
        allow: 127.0.0.1
        login-username: druid
        login-password: druid
        #禁止那些ip
        #        deny: 192.168.1.102
        #是否可以重置
        reset-enable: true
        #启用
        enabled: true
  redis:
    port: 6379
    host: 39.102.87.156
    password: Zx7895204163+
    timeout: 1000

rocketmq:
  name-server: 39.102.87.156:9876
  producer:
    group: seckillStorageGroup
    send-message-timeout: 5000

mybatis:
  type-aliases-package: com.sauvignon.seckill.pojo.entities
  mapper-locations: classpath:mybatis/mappers/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"

#自定义属性
storage-manage:
  mq:
    consumerGroup:
      dealConsumer: "commodityDealGroup"
    topic:
      paymentSideTopic: "seckill_payment_aspect_topic"
    tag:
      dealTag: "dealTag"
